---
- name: Provision jSS7 simulator
  hosts: all
  sudo: true
  tasks:
  - name: Install jSS7 deps
    yum: name={{item}}
         state=present
    with_items:
    - java-1.7.0-openjdk-devel
    - lksctp-tools
    - lksctp-tools.i686
    - unzip

  - name: Install X11
    yum: name={{item}}
         state=present
    with_items:
    - '@basic-desktop'
    - '@desktop-platform'
    - '@x11'
    - '@fonts'
    when: ansible_hostname == 'client'

  - name: Create jSS7 folder
    file: path=/opt/jSS7
          state=directory

  - name: Unarchive jSS7
    unarchive: src=files/mobicents-ss7-2.0.0.FINAL.zip
               dest=/opt/jSS7
               creates=/opt/jSS7/README.TXT

  - name: Change simulator script attributes
    file: path=/opt/jSS7/ss7/mobicents-ss7-simulator/bin/run.sh
          mode=0755

  - name: Copy simulator server config
    copy: src=files/jSS7/dsi-test-server_simulator2.xml
          dest=/opt/jSS7/ss7/mobicents-ss7-simulator/
    when: ansible_hostname == 'server'

  - name: Copy simulator client config
    copy: src=files/jSS7/dsi-test-client_simulator2.xml
          dest=/opt/jSS7/ss7/mobicents-ss7-simulator/
    when: ansible_hostname == 'client'
