---
- name: Setup common env
  hosts: all
  sudo: true
  tasks:
  - name: Set hostname
    hostname: name={{hostname}}

  - name: Set server to /etc/hosts
    lineinfile: dest=/etc/hosts
                line="{{ hostvars['server']['ansible_ssh_host'] }} server"

  - name: Set client to /etc/hosts
    lineinfile: dest=/etc/hosts
                line="{{ hostvars['client']['ansible_ssh_host'] }} client"

  - name: Install common stuff
    yum: name={{item}}
         state=present
    with_items:
    - emacs
    - git
    - mc
