---
- name: Setup the jSS7 simulator
  hosts: all
  sudo: true
  tasks:
  - name: Install jSS7 deps
    yum: name={{item}}
         state=present
    with_items:
    - java-1.7.0-openjdk-devel
    - lksctp-tools
    - lksctp-tools.i686
    - unzip

  - name: Install X11
    yum: name={{item}}
         state=present
    with_items:
    - '@basic-desktop'
    - '@desktop-platform'
    - '@x11'
    - '@fonts'
    when: ansible_hostname == 'client'

  # Workaround to make X11 work under root
  # http://www.linuxquestions.org/questions/linux-software-2/cannot-open-display-as-root-352200/
  - name: Set server to /etc/hosts
    lineinfile: dest=/etc/hosts
                line="{{ hostvars['server']['ansible_ssh_host'] }} server"

  - name: Export XAUTHORITY
    lineinfile: dest={{ ansible_env.HOME }}/.bashrc
                line="export XAUTHORITY={{ ansible_env.HOME }}/.Xauthority"

  - name: Create jSS7 folder
    file: path=/opt/jSS7
          state=directory

  - name: Unarchive jSS7
    unarchive: src=files/mobicents-ss7-2.0.0.FINAL.zip
               dest=/opt/jSS7
               creates=/opt/jSS7/README.TXT

  - name: Change simulator script attributes
    file: path=/opt/jSS7/ss7/mobicents-ss7-simulator/bin/run.sh
          mode=0755

  - name: Provision simulator server config
    template:
      src=files/jSS7/server_simulator2.xml.j2
      dest=/opt/jSS7/ss7/mobicents-ss7-simulator/server_simulator2.xml
    when: ansible_hostname == 'server'

  - name: Provision simulator client config
    template:
      src=files/jSS7/client_simulator2.xml.j2
      dest=/opt/jSS7/ss7/mobicents-ss7-simulator/client_simulator2.xml
    when: ansible_hostname == 'client'
