---
- name: Provision common env
  hosts: all
  sudo: true
  tasks:
  - name: Set hostname
    hostname: name={{hostname}}

  - name: Set server to /etc/hosts
    lineinfile: dest=/etc/hosts
                line='192.168.200.101 server'

  - name: Set client to /etc/hosts
    lineinfile: dest=/etc/hosts
                line='192.168.200.102 client'
